### ISSUE TITLE
Icon/Logo Proposal

### ISSUE THREAD

**Issue by loydjayme25** [VREMSoftwareDevelopment/WiFiAnalyzer#177] opened 2018-05-10 11:55 UTC
Good day ! I am Graphics Designer,

If the project needs logo, I am willing to give my best design for this. Thanks PO !

**Comment by VREMSoftwareDevelopment** [comment] 2018-05-10 12:02
Feel free to add your two cents to #166 and #176

Duplicate of #166 and #176

**Closed by VREMSoftwareDevelopment** 2018-05-10 12:02 UTC
