### ISSUE TITLE
Android OS 6.0.0 -  Location Service ON

### ISSUE THREAD

**Issue by VREMSoftwareDevelopment** [VREMSoftwareDevelopment/WiFiAnalyzer#23] opened 2016-04-20 00:35 UTC
Some users running Android OS 6.0.0 (Marshmallow) have reported that the location service must be enabled for the application to see WiFi networks. Marshmallow users may need to turn on the location service, even though WiFi Analyzer does not explicitly require it. This appears to be attributed to a potential issue in Android OS 6.0.0 that requires location service in order to see WiFi networks.

**Comment by morganestes** [comment] 2016-04-21 04:00
This isn't limited to Android 6. CyanogenOS 12.1.1 (Android 5.1.1) running on a OnePlus One also has this problem: denying location access with Privacy Guard prevents scanning for WiFi APs, but allowing it immediately shows access points.

**Comment by VREMSoftwareDevelopment** [comment] 2016-04-29 19:04
Link from Android Open Source Project - Issue Tracker

WifiManager#getScanResults() returns an empty array list if GPS is turned off.

[Issue](https://code.google.com/p/android/issues/detail?id=185370#c1)

[Solution](https://code.google.com/p/android/issues/detail?id=185370#c18)

**Comment by VREMSoftwareDevelopment** [comment] 2016-08-16 12:14
List of phones running Android 6.0 that have known to have issue.
- Motorola: Moto G (2nd Gen)
- Motorola: Moto X Pure Edition
- Lenovo Mobile: Lenovo VIBE X3 Lite

**Comment by renatus** [comment] 2016-11-14 04:47
Actually looks like it's not a bug, it's a feature:
[https://developer.android.com/about/versions/marshmallow/android-6.0-changes.html#behavior-hardware-id](url)

> To access the hardware identifiers of nearby external devices via Bluetooth and Wi-Fi scans, your app must now have the ACCESS_FINE_LOCATION or ACCESS_COARSE_LOCATION permissions

And it's more or less reasonable behavior, since, if you have data about WIFI signals around you, you can clearly get a location as well.

**Comment by VREMSoftwareDevelopment** [comment] 2016-11-14 23:57
### APK23 or later (Android OS 6 or later)
In order for the applications to use WiFi scanning the ACCESS_FINE_LOCATION or ACCESS_COARSE_LOCATION permissions is required.  The application must request permission at run time [https://developer.android.com/training/permissions/requesting.html](https://developer.android.com/training/permissions/requesting.html).

### APK22 or prior (Android OS 5.1 or prior)
In order for the applications to use WiFi scanning ACCESS_FINE_LOCATION or ACCESS_COARSE_LOCATION permission is **NOT** required. Installing the application build using APK22 or prior on the device running Android OS 6 or above should not force user to give ACCESS_FINE_LOCATION or ACCESS_COARSE_LOCATION permission to the application.  

> old rules will be still applied to it for compatibility reasons

The old rules are broken on the some devices . Please take a look at [https://code.google.com/p/android/issues/detail?id=185370#c1](https://code.google.com/p/android/issues/detail?id=185370#c1)

**Comment by davidgro** [comment] 2016-11-18 03:04
I don't know if it's been made explicit here yet, but this is a **Blocking Issue** on Marshmallow. I found no way to grant the app the permission it needs without it making the request, and it isn't making the request.

(Of course location is enabled phone-wide, but that's not enough obviously)

**Comment by VREMSoftwareDevelopment** [comment] 2016-11-18 22:45
Android OS **6.0.0** introduced new permission model, at the same time, permissions for some existing APK API were changed. (ie WiFi scanner API)
[https://developer.android.com/about/versions/marshmallow/android-6.0-changes.html#behavior-hardware-id](https://developer.android.com/about/versions/marshmallow/android-6.0-changes.html#behavior-hardware-id)

By introducing permission changes to existing APK API, backward compatibility for the applications written using previous APK versions was broken. 
(ie. Any application written to use WiFi scanner API required location service to be enabled in order to work properly)
[https://code.google.com/p/android/issues/detail?id=185370](https://code.google.com/p/android/issues/detail?id=185370)

This issues was fixed in the Android OS **6.0.1**.
[https://code.google.com/p/android/issues/detail?id=185370#c18](https://code.google.com/p/android/issues/detail?id=185370#c18)

WiFi Analyzer is written using APK 22 - Android OS 5.1. It does not require and does not need location service, since it was written for Android OS 5.1.

**Comment by davidgro** [comment] 2016-11-30 01:04
Ok, so it's an OS issue and it's been fixed in an update that not everyone has - Can the app please just request the permission so it can work for everyone? I am not seeing why this is a hardship.

**Comment by VREMSoftwareDevelopment** [comment] 2016-12-03 20:34
@davidgro Yes, it is possible to request the permission in the application (APK 23 has it).
This will require to maintain two source code branches since the code will be different between APK 22 and 23.
Would you like to help with this, it would be great to add another contributor to this project.

**Closed** 2017-04-14 13:38 UTC
Labels: FAQ, question

**Comment by wino45** [comment] 2017-06-03 10:28
My Android is 7.1, the location service is on and I got no data.

**Comment by VREMSoftwareDevelopment** [comment] 2017-06-03 11:13
@wino45 Very strange. 
Can you please provide the following:
- Device information
- Application About screenshot

Thanks

**Comment by wino45** [comment] 2017-06-03 13:00
![screenshot_20170603-145652](https://cloud.githubusercontent.com/assets/5285455/26753724/4d551aea-486d-11e7-9478-89faa6247767.png)
![screenshot_20170603-145720](https://cloud.githubusercontent.com/assets/5285455/26753727/53f4f492-486d-11e7-8d7a-5a122f907ef5.png)
![screenshot_20170603-145740](https://cloud.githubusercontent.com/assets/5285455/26753729/5a8f97b2-486d-11e7-8d84-dd879afb72c9.png)

**Comment by VREMSoftwareDevelopment** [comment] 2017-06-03 14:39
Thanks for the information.

Unfortunately, we do not have this specific physical device for testing (Google Pixel C - Android 7.1.2). 
We were able to test the application using virtual machine (Google Pixel C - Version 7.1.1) and it does work.

**Maybe try different Location modes and see if one of them works:**

- High accuracy
- Battery saving
- Device only

![image](https://cloud.githubusercontent.com/assets/6217364/26754418/8ef9d65e-4848-11e7-9361-d8118f57e0f7.png)

By any chance, do you have any knowledge in Android development? 
Maybe you can help us to investigate this specific issues.

**Comment by wino45** [comment] 2017-06-03 15:20
I found the solution. The user I was using was not the device owner but normal user. When I installed wifi analyzer as device owner it is working. So the problem is not location but type of the user the wifi analyzer is run by. Thanks for you support. 

Maybe you can test the user type and adjust the displayed information?

**Comment by VREMSoftwareDevelopment** [comment] 2017-06-03 17:53
@wino45 We will see what we can about it.
