### ISSUE TITLE
Option to connect to network

### ISSUE THREAD

**Issue by ghost** [VREMSoftwareDevelopment/WiFiAnalyzer#42] opened 2016-08-01 19:33 UTC
Please make an option to connect/disconnect from the selected WiFi network.

**Comment by mike-melo** [comment] 2016-08-05 14:28
This is an interesting idea for a feature. Would you be able to elaborate in more detail on when and why you would use this option? We're curious to understand where you're coming from.

Thank you,
The VREM Development Team

**Comment by z751** [comment] 2016-08-05 23:45
Sure.  For example if you are looking for an open WiFi and find one, you should be able to select it rather than having to go open the settings menu.  Also I find it odd that you can select a network and nothing happens other than it gets highlighted.  Others may think something is not working.  

I would like to use it as a replacement for the WiFi settings menu.  Since this app also gives the type of password required and more detailed signal information.

**Comment by z751** [comment] 2016-08-15 17:49
@mike-melo is this something we can look forward to in the future?

**Comment by mike-melo** [comment] 2016-08-16 15:12
Potentially in the near future, but unfortunately not in the short term. We're definitely keeping the item in our bucket list. By any chance, do you have any knowledge in Android development? When we don't have an opportunity to implement a feature, we encourage developers to fork the project.

**Comment by z751** [comment] 2016-08-17 15:32
Unfortunately I do not.

**Comment by GHubNH** [comment] 2016-08-28 14:46
Using a wifi scanner is a far superior way to select between available networks than the Android system. I'm very much in favour of this function. The farproc version has an add on for this functionality.

**Comment by zanzani** [comment] 2018-06-14 10:01
Please still consider this. It would make the app twice as useful and will make me delete a closed-source app.
Next wish after implementing will be to make it capable to connect wpa-enterprise APs.
Thanks!

**Comment by rattanaksamath** [comment] 2019-06-30 14:00
Duplicate of #

**Closed** 2019-07-10 23:57 UTC
Labels: enhancement, wontfix
