### ISSUE TITLE
current version not available in F-Droid

### ISSUE THREAD

**Issue by Krawei** [VREMSoftwareDevelopment/WiFiAnalyzer#292] opened 2020-04-05 10:59 UTC
Dear team,

when I take a look on google play store the current version is 2.1.2.52, in the F-Droid store the current version is 2.1.1.51.

What's the reason for this gap? Is there a bug in the build process?

Please fix this.

Kind Regards,

Krawei

**Comment by ldmpub** [comment] 2020-04-05 11:05
Duplicate of#291

**Closed** 2020-04-05 11:31 UTC
